### ISSUE TITLE
Bug: "101 tx listeners added"

### ISSUE THREAD

**Issue by paulkernfeld** [paulkernfeld/burnie#1]
I'm seeing this bug regularly after several burns are verified, although I'm not sure that it's actually causing any real problems.

@mappum I think this may be due to a problem in webcoin, but also maybe not.

```
paul ~/projects/burnie master $ node example.js
  burnie Burnie starting... +0ms
Input pubkey hash 2ee69ca3fc95ce4e0864b16e94f1e2be9afe9682
block height 278622
block time Sat Jan 04 2014 22:59:03 GMT+0100 (CET)
satoshis 2406492

Input pubkey hash 8c20ca01f3809027db23f54c06ae1e33e370e192
block height 278629
block time Sat Jan 04 2014 23:46:03 GMT+0100 (CET)
satoshis 4990000

Input pubkey hash c45d1b0230272ee5c1e6b0f6a1835ac475be4923
block height 278630
block time Sat Jan 04 2014 23:53:25 GMT+0100 (CET)
satoshis 40000

Unrecognized inputs
block height 278630
block time Sat Jan 04 2014 23:53:25 GMT+0100 (CET)
satoshis 4980000

Unrecognized inputs
block height 278631
block time Sat Jan 04 2014 23:53:56 GMT+0100 (CET)
satoshis 4970000

Input pubkey hash eba4bd1f92ffb694f65a75ece32694b298a3e912
block height 278642
block time Sun Jan 05 2014 01:56:22 GMT+0100 (CET)
satoshis 9480000

Input pubkey hash bb8193f502674dcf02fae052dc98b27ce3a466e3
block height 278644
block time Sun Jan 05 2014 02:08:23 GMT+0100 (CET)
satoshis 9490000

Unrecognized inputs
block height 278644
block time Sun Jan 05 2014 02:08:23 GMT+0100 (CET)
satoshis 742856

Input pubkey hash 112766f716fb358c4717e4a270aaeeb47dda81c5
block height 278689
block time Sun Jan 05 2014 07:25:41 GMT+0100 (CET)
satoshis 9990000

Input pubkey hash 66388596b12ff502cae0f62b75233b5efcb233af
block height 278691
block time Sun Jan 05 2014 07:35:16 GMT+0100 (CET)
satoshis 9990000

Input pubkey hash 07978baeacaa3f1893c6900dba398836ae30daf8
block height 278691
block time Sun Jan 05 2014 07:35:16 GMT+0100 (CET)
satoshis 9990000

Unrecognized inputs
block height 278718
block time Sun Jan 05 2014 10:45:32 GMT+0100 (CET)
satoshis 6642

Input pubkey hash ffacbcfe3e2836902f3bc6f830f25af010a01fcf
block height 278768
block time Sun Jan 05 2014 16:53:11 GMT+0100 (CET)
satoshis 48880000

Input pubkey hash 6f498d5b42a50ed927828c5353396659d5f68ed4
block height 278791
block time Sun Jan 05 2014 19:25:26 GMT+0100 (CET)
satoshis 15430

Input pubkey hash 48626ad02b45d3506aa3d5bc4c0df99516245051
block height 278796
block time Sun Jan 05 2014 19:40:24 GMT+0100 (CET)
satoshis 79980000

Input pubkey hash 48626ad02b45d3506aa3d5bc4c0df99516245051
block height 278797
block time Sun Jan 05 2014 20:02:28 GMT+0100 (CET)
satoshis 69970000

Input pubkey hash 09947c36f4a2196ee286a81e6652c19474271473
block height 278800
block time Sun Jan 05 2014 20:42:18 GMT+0100 (CET)
satoshis 7680000

Unrecognized inputs
block height 278800
block time Sun Jan 05 2014 20:42:18 GMT+0100 (CET)
satoshis 70000

Input pubkey hash 8ee27a54fe96b2c23dc78002fd31e3c6d95b97b2
block height 278828
block time Mon Jan 06 2014 00:53:54 GMT+0100 (CET)
satoshis 289600

Input pubkey hash 1bf51f9d78261bac575bf7f49f0e41a44b7c2cb7
block height 278885
block time Mon Jan 06 2014 07:09:43 GMT+0100 (CET)
satoshis 860000

Input pubkey hash 7207f2af74ea5122fc8916208eb75d26bc4c2baa
block height 278888
block time Mon Jan 06 2014 08:03:25 GMT+0100 (CET)
satoshis 3950000

Input pubkey hash 1bf51f9d78261bac575bf7f49f0e41a44b7c2cb7
block height 278888
block time Mon Jan 06 2014 08:03:25 GMT+0100 (CET)
satoshis 80000

Input pubkey hash 2373592bd5fc83e1f3aaf037d841ad85d0e2fac1
block height 278899
block time Mon Jan 06 2014 10:00:04 GMT+0100 (CET)
satoshis 40000

Input pubkey hash 0502725f7459a84ac0a93b159d0e9029eed6d28e
block height 278920
block time Mon Jan 06 2014 12:52:46 GMT+0100 (CET)
satoshis 9930000

Input pubkey hash 3383eca7ca3ed333d81099c87d2589f81d5a547e
block height 278922
block time Mon Jan 06 2014 13:22:16 GMT+0100 (CET)
satoshis 5020000

Input pubkey hash 56a9979d59d25bdeb9a8205846af5619bb83a275
block height 278922
block time Mon Jan 06 2014 13:22:16 GMT+0100 (CET)
satoshis 5030000

Input pubkey hash 3800d56b2e941908c239e092eff8d5b4c368e59c
block height 278923
block time Mon Jan 06 2014 13:33:10 GMT+0100 (CET)
satoshis 3110557

Unrecognized inputs
block height 278923
block time Mon Jan 06 2014 13:33:10 GMT+0100 (CET)
satoshis 4961912

Input pubkey hash 3425ffd09e713554fe91104fd53436dcefea607f
block height 278923
block time Mon Jan 06 2014 13:33:10 GMT+0100 (CET)
satoshis 70000

Input pubkey hash 5eb81458fa477ab191f6a386d1fb459b158924db
block height 278925
block time Mon Jan 06 2014 13:47:22 GMT+0100 (CET)
satoshis 9899890000

Input pubkey hash b37abc88934b4e0531b49783159cf6b70a1f4e81
block height 278925
block time Mon Jan 06 2014 13:47:22 GMT+0100 (CET)
satoshis 8685611439

Input pubkey hash d3297d8b13512c0b1b97dbc7706a7c79ff69daac
block height 278928
block time Mon Jan 06 2014 14:08:37 GMT+0100 (CET)
satoshis 70000

Input pubkey hash 43e144940d6d6f7ed0ebdc4185562e9485d0a520
block height 278928
block time Mon Jan 06 2014 14:08:37 GMT+0100 (CET)
satoshis 70000

Input pubkey hash eb860f09862766748ffca53d3b8df92120de9d87
block height 278928
block time Mon Jan 06 2014 14:08:37 GMT+0100 (CET)
satoshis 30380714

Input pubkey hash e8a86b49ef2f38243a65a2a371fc46bd1558e22a
block height 278936
block time Mon Jan 06 2014 14:52:32 GMT+0100 (CET)
satoshis 70000

(node) warning: possible EventEmitter memory leak detected. 101 tx listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:252:17)
    at BlockStream._getTransactions (/Users/paul/projects/burnie/node_modules/webcoin/lib/blockStream.js:159:14)
    at BlockStream._onMerkleBlock (/Users/paul/projects/burnie/node_modules/webcoin/lib/blockStream.js:117:8)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at null.<anonymous> (/Users/paul/projects/burnie/node_modules/webcoin/lib/peerGroup.js:104:12)
    at emitOne (events.js:95:20)
    at emit (events.js:182:7)
    at Peer._readMessage (/Users/paul/projects/burnie/node_modules/bitcore-p2p/lib/peer.js:221:10)
    at Peer._readMessage (/Users/paul/projects/burnie/node_modules/bitcore-p2p/lib/peer.js:222:10)
    at Socket.<anonymous> (/Users/paul/projects/burnie/node_modules/bitcore-p2p/lib/peer.js:167:10)
Input pubkey hash c795ce9035d8984054661d7826076291f67beb95
block height 278942
block time Mon Jan 06 2014 15:53:37 GMT+0100 (CET)
satoshis 80000

Input pubkey hash 8d675cb3521eaa5f4e61a6cfd4f7e9b38aa5b9fc
block height 278950
block time Mon Jan 06 2014 16:44:50 GMT+0100 (CET)
satoshis 872180

...
...
```

**Comment by mappum** [comment]
I'll look into this, the problem is probably with Webcoin. Now I realize I
haven't really tested with large volumes of matched transactions, so there
are probably a few optimizations to make.

**Comment by mappum** [comment]
BTW, this is awesome :+1:

**Comment by paulkernfeld** [comment]
Thanks! :D
