### ISSUE TITLE
Key not found in database

### ISSUE THREAD

**Issue by paulkernfeld** [paulkernfeld/burnie#12]
I occasionally see errors such as this:

```
paul ~/projects/burnie master $ git commit -am "This is 0.5.2"

> burnie@0.5.2 test /Users/paul/projects/burnie
> standard && tape test.js

TAP version 13
# get counterparty burns
  burnie new burnie +0ms 1CounterpartyXXXXXXXXXXXXXXXUWLpVr 278208
ok 1 saw a peer
  burnie chain tip is now ready +2s 278209 278208
  burnie burnie will start txs at height +0ms 278208
  burnie burnie starting txs... +2ms
  burnie headers at +238ms 279000
  burnie headers at +224ms 280000

events.js:160
      throw er; // Unhandled 'error' event
      ^
NotFoundError: Key not found in database [9xxlbol/AMvCfzMoV2D271GMNhNi3QLZAgAAAAAAAAA=]
    at /Users/paul/projects/burnie/node_modules/levelup/lib/levelup.js:217:15
    at Immediate.callNext (/Users/paul/projects/burnie/node_modules/memdown/memdown.js:168:47)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by paulkernfeld** [comment]
Hopefully this is fixed in commit [97e34f3](https://github.com/paulkernfeld/burnie/commit/97e34f37accffbfc32a49b8a6564e339748efb82)!
